### PR TITLE
R16B01 compatibility changes.

### PR DESCRIPTION
**Pull request by evanmcc**
update hash functions for R16B01

### CODE REVIEW

**Comment by evanmcc** [comment]
updated.

**Comment by joedevivo** [comment]
Do we care about this warning?

```
Compiled src/prf.erl
src/prf_crypto.erl:18: Warning: crypto:des_cbc_encrypt/3 is deprecated and will be removed in in a future release; use crypto:block_encrypt/4
src/prf_crypto.erl:25: Warning: crypto:des_cbc_decrypt/3 is deprecated and will be removed in in a future release; use crypto:block_decrypt/4
src/prf_crypto.erl:28: Warning: crypto:md5/1 is deprecated and will be removed in in a future release; use crypto:hash/2
```

**Comment by evanmcc** [comment]
you shouldn't be seeing it at all.  You're sure you're on the branch?

**Comment by joedevivo** [comment]
I was not on the branch, I'll be in the corner.

**Comment by joedevivo** [comment]
Branch builds fine without warnings, basic redbug test works as expected.

```
9>  redbug:start(100000, 2, {erlang,now,[return,stack]}).
ok        
10> erlang:now().

13:43:12 <{erlang,apply,2}> {erlang,now,[]}
  "shell:eval_loop/3 "
{1373,920992,75963}
  "shell:eval_exprs/7 "
  "shell:exprs/7 "

13:43:12 <{erlang,apply,2}> {erlang,now,0} -> {1373,920992,75963}
quitting: msg_count
11> 
```

**Comment by joedevivo** [comment]
+1 do it!

**Comment by massemanet** [comment]
fixed in 0.74/master

**Pull request merged**
